### ISSUE TITLE
Source Map Warning: `weekday.ts` Not Found in `rrule` Package

### ISSUE THREAD

**Issue by DavidHinkelmann** [jkbrzt/rrule#633] opened 2024-09-02 14:22 UTC
I am encountering a warning related to source maps when using the rrule package in my project. The warning indicates that Webpack's source-map-loader is unable to locate the weekday.ts file. This occurs during the build process.

### Steps to Reproduce:

Install the rrule package version 2.8.1 in a project using Webpack.
Configure Webpack to use source-map-loader.
Run the Webpack build process.

**Expected Behavior:** The build should complete without warnings related to missing source files.

**Actual Behavior:**  The following warning appears during the build:
```
WARNING in ./node_modules/.pnpm/rrule@2.8.1/node_modules/rrule/dist/esm/weekday.js
Module Warning (from ./node_modules/.pnpm/source-map-loader@3.0.2_webpack@5.88.2/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/davidDocuments/project/project-name/node_modules/.pnpm/rrule@2.8.1/node_modules/rrule/src/weekday.ts' file: Error: ENOENT: no such file or directory, open '/Users/david/Documents/project/project-name/node_modules/.pnpm/rrule@2.8.1/node_modules/rrule/src/weekday.ts'
```

**Environment** :
rrule version: 2.8.1
Webpack version: 5.88.2
source-map-loader version: 3.0.2
Node.js version:  v20.14.0
Operating System: Mac Os Sonoma 14.6.1 | also tryed on Windows 11 and Ubuntu
Timezone: GMT+2

please ask if you have questions about my Issue 🤗

**Comment by dargmuesli** [comment] 2024-09-04 08:19
This seems to be a duplicate of #303 and #522 if I'm not mistaken and should be resolves by #634.

**Closed as not planned** 2024-09-04 08:56 UTC
